flowchart TD
    A([開始]) --> B
    B[Excelの「Sheet1」のA1セルの値を変数xに代入する] --> C{変数xに文字列「test」が含まれているか}
    C --> |Yes| D[変数xに「test」の文字列が含まれる旨のポップアップメッセージを表示する]
    C --> |No| E[変数xに「test」の文字列が含まれない旨のポップアップメッセージを表示する]
    D--> F([終了])
    E--> F([終了])
    