flowchart TD
    N001([開始]) --> N002["n を入力"]
    N002 --> N003["l を 0 に設定"]
    N003 --> N004["r を 0 に設定"]
    N004 --> N005["i を 0 に設定"]

    N005 --> N006{"i は n 未満か"}
    N006 -- "いいえ" --> N999([終了])

    N006 -- "はい" --> N007["1 行入力して空白で分割"]
    N007 --> N008["p に 1 番目の値を設定"]
    N008 --> N009["s に 2 番目の値を設定"]
    N009 --> N010["w に 3 番目の値を整数として設定"]

    N010 --> N011{"p は 1 か"}
    N011 -- "はい" --> N012{"s は L か"}
    N012 -- "はい" --> N013["l に l + w を設定"]
    N012 -- "いいえ" --> N014{"s は R か"}
    N014 -- "はい" --> N015["r に r + w を設定"]
    N014 -- "いいえ" --> N016["変更なし"]
    N011 -- "いいえ" --> N017["p が 1 ではない"]

    N013 --> N018{"p は 3 か"}
    N015 --> N018
    N016 --> N018
    N017 --> N018

    N018 -- "はい" --> N019{"s は L か"}
    N019 -- "はい" --> N020["l に l - w を設定"]
    N020 --> N021["r に r + w を設定"]
    N019 -- "いいえ" --> N022["r に r - w を設定"]
    N022 --> N023["l に l + w を設定"]
    N018 -- "いいえ" --> N024["p が 3 ではない"]

    N021 --> N025{"p は 2 か"}
    N023 --> N025
    N024 --> N025

    N025 -- "はい" --> N026{"s は L か"}
    N026 -- "はい" --> N027["l に l - w を設定"]
    N026 -- "いいえ" --> N028["r に r - w を設定"]
    N025 -- "いいえ" --> N029["p が 2 ではない"]

    N027 --> N030{"l は r より大きいか"}
    N028 --> N030
    N029 --> N030

    N030 -- "はい" --> N031["出力：&gt;"]
    N030 -- "いいえ" --> N032{"l は r と等しいか"}

    N032 -- "はい" --> N033["出力：="]
    N032 -- "いいえ" --> N034{"l は r より小さいか"}

    N034 -- "はい" --> N035["出力：&lt;"]
    N034 -- "いいえ" --> N036["出力なし"]

    N031 --> N037["i に i + 1 を設定"]
    N033 --> N037
    N035 --> N037
    N036 --> N037

    N037 --> N006
