flowchart TD
    A([開始]) --> B
    B[変数aに100を代入する] --> C 
    C[変数bに2を代入する] --> D 
    D[変数cに50を代入する] --> E 
    E[変数aの値に変数bの値をかけた結果を変数dに代入する]　--> F 
    F[変数dの値に変数cの値をたした結果を画面に表示する]　--> G 
    G([終了])