flowchart TD
    A([開始]) --> B
    B[Excelの「Sheet1」のA1セルの値を変数xに代入する] --> C{変数xの値は1か}
    C --> |Yes| D[「グー」の文字列を画面のポップアップメッセージに表示する]
    C --> |No| E{変数xの値は2か}
    E --> |Yes| F[「チョキ」の文字列を画面のポップアップメッセージに表示する]
    E --> |No| G[「パー」の文字列を画面のポップアップメッセージに表示する]

    D --> H
    F --> H
    G --> H
    H([終了])
    